name: dart_ws
description: A command line application for managing AWS setups
# version: 1.0.0
# homepage: https://www.humancaching.com
# author: Bryan Riley <brileydeveloper@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
